name: Ubuntu Latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish-linux:
    uses: ./.github/workflows/UBUNTU_LATEST_REUSABLE.yml
    with:
      v8_branch: 11.3.244.11
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-mac:
    uses: ./.github/workflows/MAC_LATEST_REUSABLE.yml
    with:
      v8_branch: 11.3.244.11
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
