name: Ubuntu Latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  V8_BRANCH: 11.6.189.19

jobs:

  get-v8-version:
    uses: ./.github/workflows/GET_V8_VERSION.yml

  build-and-publish-linux-x64-release:
    needs: [get-v8-version]
    uses: ./.github/workflows/UBUNTU_LATEST_REUSABLE.yml
    with:
      v8_branch: ${{ needs.get-v8-version.outputs.V8_VERSION }}
      build_type: release
      arch: x64
      copy_headers: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-linux-x64-debug:
    needs: [get-v8-version]
    uses: ./.github/workflows/UBUNTU_LATEST_REUSABLE.yml
    with:
      v8_branch: ${{ needs.get-v8-version.outputs.V8_VERSION }}
      build_type: debug
      arch: x64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-linux-arm64-release:
    needs: [get-v8-version]
    uses: ./.github/workflows/UBUNTU_LATEST_REUSABLE.yml
    with:
      v8_branch: ${{ needs.get-v8-version.outputs.V8_VERSION }}
      build_type: release
      arch: arm64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-linux-arm64-debug:
    needs: [get-v8-version]
    uses: ./.github/workflows/UBUNTU_LATEST_REUSABLE.yml
    with:
      v8_branch: ${{ needs.get-v8-version.outputs.V8_VERSION }}
      build_type: debug
      arch: arm64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-mac-x64-release:
    needs: [get-v8-version]
    uses: ./.github/workflows/MAC_LATEST_REUSABLE.yml
    with:
      v8_branch: ${{ needs.get-v8-version.outputs.V8_VERSION }}
      build_type: release
      arch: x64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-mac-x64-debug:
    needs: [get-v8-version]
    uses: ./.github/workflows/MAC_LATEST_REUSABLE.yml
    with:
      v8_branch: ${{ needs.get-v8-version.outputs.V8_VERSION }}
      build_type: debug
      arch: x64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-mac-arm64-release:
    needs: [get-v8-version]
    uses: ./.github/workflows/MAC_LATEST_REUSABLE.yml
    with:
      v8_branch: ${{ needs.get-v8-version.outputs.V8_VERSION }}
      build_type: release
      arch: arm64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-mac-arm64-debug:
    needs: [get-v8-version]
    uses: ./.github/workflows/MAC_LATEST_REUSABLE.yml
    with:
      v8_branch: ${{ needs.get-v8-version.outputs.V8_VERSION }}
      build_type: debug
      arch: arm64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
