name: Mac Latest

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  v8_version: 10.8.168.21

jobs:

  build:

    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install Pre Requisite
        run: |
          brew install ninja
      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Checkout v8
        run: |
          export PATH="${PATH}:$(pwd)/depot_tools/"
          gclient
          mkdir v8
          cd v8
          fetch v8
          cd v8
          git checkout ${{ env.v8_version }}
      - name: Build v8
        run: |
          cd v8/v8/
          #./tools/dev/v8gen.py x64.release -- v8_monolithic=true v8_use_external_startup_data=false use_custom_libcxx=false treat_warnings_as_errors=false
          #ninja -C out.gn/x64.release v8_monolith
          ./tools/dev/v8gen.py arm64.release -- 'target_cpu="arm64" v8_monolithic=true v8_use_external_startup_data=false use_custom_libcxx=false treat_warnings_as_errors=false'
          ninja -C out.gn/arm64.release v8_monolith
      - name: Copy build artifacts out of container
        run: |
          mkdir s3uploads
          #cp v8/v8/out.gn/x64.release/obj/libv8_monolith.a s3uploads/libv8_monolith.${{ env.v8_version }}.x64.apple-darwin.a
          cp v8/v8/out.gn/arm64.release/obj/libv8_monolith.a s3uploads/libv8_monolith.${{ env.v8_version }}.arm64.apple-darwin.a
      - name: Configure s3cmd
        uses: s3-actions/s3cmd@v1.2.0
        with:
          provider: aws
          region: us-east-2
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_KEY_ID }}
      - name: Upload artifacts
        run: |
          s3cmd put -P s3uploads/* s3://redismodules/redisgears/dependencies/
