name: Ubunru Build and Publish

on:
  workflow_call:
    inputs:
      v8_branch:
        required: true
        type: string
      build_type:
        required: true
        type: string
      arch:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_KEY_ID:
        required: true

jobs:

  build-and-publish:

    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install Pre Requisite
        run: |
          brew install ninja
      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Checkout v8
        run: |
          export PATH="${PATH}:$(pwd)/depot_tools/"
          gclient
          mkdir v8
          cd v8
          fetch v8
          cd v8
          git checkout ${{ inputs.v8_branch }}
      - name: Build v8
        run: |
          bash ./build_mac_${{ inputs.arch }}.${{ inputs.build_type }}.bash
      - name: Copy build artifacts out of container
        run: |
          mkdir s3uploads
          cp v8/v8/out.gn/${{ inputs.arch }}.${{ inputs.build_type }}/obj/libv8_monolith.a s3uploads/libv8_monolith.${{ inputs.v8_branch }}.${{ inputs.arch }}.${{ inputs.build_type }}.apple-darwin.a
      - name: Configure s3cmd
        uses: s3-actions/s3cmd@v1.2.0
        with:
          provider: aws
          region: us-east-2
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_KEY_ID }}
      - name: Upload artifacts
        run: |
          s3cmd put -P s3uploads/* s3://redismodules/redisgears/dependencies/
