name: Nightly master build

on:

  workflow_dispatch:

  schedule:
    - cron: "0 5 * * *"
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish-linux-x64-release:
    uses: ./.github/workflows/UBUNTU_LATEST_REUSABLE.yml
    with:
      v8_branch: main
      build_type: release
      arch: x64
      copy_headers: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-linux-x64-debug:
    uses: ./.github/workflows/UBUNTU_LATEST_REUSABLE.yml
    with:
      v8_branch: main
      build_type: debug
      arch: x64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-linux-arm64-release:
    uses: ./.github/workflows/UBUNTU_LATEST_REUSABLE.yml
    with:
      v8_branch: main
      build_type: release
      arch: arm64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-linux-arm64-debug:
    uses: ./.github/workflows/UBUNTU_LATEST_REUSABLE.yml
    with:
      v8_branch: main
      build_type: debug
      arch: arm64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-mac-x64-release:
    uses: ./.github/workflows/MAC_LATEST_REUSABLE.yml
    with:
      v8_branch: main
      build_type: release
      arch: x64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
  
  build-and-publish-mac-x64-debug:
    uses: ./.github/workflows/MAC_LATEST_REUSABLE.yml
    with:
      v8_branch: main
      build_type: debug
      arch: x64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-mac-arm64-release:
    uses: ./.github/workflows/MAC_LATEST_REUSABLE.yml
    with:
      v8_branch: main
      build_type: release
      arch: arm64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-mac-arm64-debug:
    uses: ./.github/workflows/MAC_LATEST_REUSABLE.yml
    with:
      v8_branch: main
      build_type: debug
      arch: arm64
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

