name: Nightly master build

on:

  workflow_dispatch:

  schedule:
    - cron: "0 5 * * *"

jobs:
  build-and-publish-linux:
    uses: ./.github/workflows/UBUNTU_LATEST_REUSABLE.yml
    with:
      v8_branch: main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}

  build-and-publish-mac:
    uses: ./.github/workflows/MAC_LATEST_REUSABLE.yml
    with:
      v8_branch: main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
